    SUBROUTINE MUSKTODINI_ALLOCA(IOP)
	!
	USE VARS_MAIN
    USE MUSKTODINI_VARS
	!USE VARS_CALIB
    
	IMPLICIT NONE	
	INTEGER IOP
    SAVE

	SELECT CASE (IOP) !VERIFICA SE ALLOCA OU DEALLOCA
    CASE (0) ! ALLOCA
      
        ALLOCATE (HFL_TOD(NC,NT))
        ALLOCATE (RUGMAN_TOD(NC))        
        ALLOCATE (ZTAB_TOD(102,NC),VTAB_TOD(102,NC),ATAB_TOD(102,NC))        
        ALLOCATE (ATAB1_TOD(102,NC),ATAB2_TOD(102,NC),ATAB3_TOD(102,NC))
        ALLOCATE (QTAB1_TOD(102,NC),QTAB2_TOD(102,NC),QTAB3_TOD(102,NC))  
        ALLOCATE (JTAB_TOD(NC))
        ALLOCATE (DQDA_TOD(102,NC))
    
    CASE (1) ! DEALLOCA
    
        DEALLOCATE (HFL_TOD)
        DEALLOCATE (RUGMAN_TOD)        
        DEALLOCATE (ZTAB_TOD,VTAB_TOD,ATAB_TOD)        
        DEALLOCATE (ATAB1_TOD,ATAB2_TOD,ATAB3_TOD)
        DEALLOCATE (QTAB1_TOD,QTAB2_TOD,QTAB3_TOD) 
        DEALLOCATE (JTAB_TOD)
        DEALLOCATE (DQDA_TOD)
    
		
        
	CASE DEFAULT
		STOP ' ERRO: IOP DESCONHECIDO NO ROTINA ALLOCA_TODINI!!!'
	END SELECT 

    END SUBROUTINE    